name: Run bot
on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  

jobs:
  build:
    name: arbitrage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          architecture: x64
      - name: Install 
        run: pip3 install .
      - name: Install dependencies
        run: python run arbitrage-bot/bot.py